name: femi_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.13.4
  http: ^1.6.0
  flutter_secure_storage: ^11.0.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0

  # Nouveaux packages ajoutés pour le Chat Femi (Audio, Images, Multipart)
  http_parser: ^4.0.2
  image_picker: ^1.1.0
  record: ^7.1.1
  path_provider: ^2.1.2

  # Ajouté pour le bouton/bandeau "Continuer sur WhatsApp"
  url_launcher: ^6.3.0

  # Ajouté pour afficher la page de paiement FedaPay dans l'app
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true